# -*- coding: utf-8 -*-
"""2024 best dribblers top 5 leagues.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16dqhVODNav-CX0VcY7wJN-VuiuC79E9H
"""

!pip install soccerdata

from soccerdata import FBref

reader = FBref(seasons='2324')

players = reader.read_player_season_stats(stat_type='possession')

players.columns

players.head()

players.columns = ['_'.join(col).strip() for col in players.columns.values]

players.head()

flat_players = players.reset_index()

flat_players.head()

flat_players.info()

flat_players['league'].unique()

best_dribblers = flat_players[flat_players['Take-Ons_Succ'] > 50]

top_dribblers = best_dribblers.sort_values(by='Take-Ons_Succ', ascending=False).head(50)

#df['new_column'] = df['existing_column'].apply(lambda x: 'Yes' if x == 3 else 'No')

top_dribblers['PL or Not'] = top_dribblers['league'].apply(lambda x: 'PL' if x == 'ENG-Premier League' else 'Other League')
wing_dribblers = best_dribblers[best_dribblers['player'].isin(['Cody Gakpo', 'Marcus Rashford', 'Bukayo Saka', 'Gabriel Jesus', 'Khvicha Kvaratskhelia', 'Vinicius Júnior', 'Jamal Musiala', 'Michael Olise', 'Leroy Sane', 'Bradley Barcola'])]

print(wing_dribblers[['player', 'Take-Ons_Succ', 'Take-Ons_Succ%']])

top_dribblers['league'].value_counts()

pip install adjustText

from adjustText import adjust_text


plt.figure(figsize=(11, 8))
scatter_plot = sns.scatterplot(top_dribblers, x="Take-Ons_Succ", y="Take-Ons_Succ%")
plt.xlabel('Successful Take-ons')
plt.ylabel('Take-on Success %')
plt.title("Top 50 Dribblers in Europe's Top Five Leagues(take-ons completed) in 23/24")

# Annotate each point with its label
texts = []
for i, row in top_dribblers.iterrows():
    texts.append(scatter_plot.text(row['Take-Ons_Succ'], row['Take-Ons_Succ%'], row['player'], fontsize=10, ha='right'))

# Adjust the layout to prevent labels from overlapping
adjust_text(texts)

plt.show()

print(top_dribblers[['player', 'pos_','Take-Ons_Succ', 'Take-Ons_Succ%']].sort_values(by='Take-Ons_Succ', ascending=False))

